version: "3.9"

services:
  db:
    image: postgres:15
    container_name: shodh-db
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: shodh
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/src/main/resources/initdb:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shodh-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shodh
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
      JUDGE_IMAGE: shodh-judge:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shodh-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:8080
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db-data:
